//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ks.Items.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public string ItemId { get; set; }
        public Nullable<decimal> ProdId { get; set; }
        public string ProductName { get; set; }
        public string PartNum { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string OrdId { get; set; }
        public string IdInvoince { get; set; }
    }
}
