//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ks.Customer.ReferenciaSony {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios.SonyQuoteService.com/", ConfigurationName="ReferenciaSony.SonyQuoteService")]
    public interface SonyQuoteService {
        
        [System.ServiceModel.OperationContractAttribute()]
        void initiate();
        
        [System.ServiceModel.OperationContractAttribute()]
        void initiateAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SonyQuoteServiceChannel : Ks.Customer.ReferenciaSony.SonyQuoteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SonyQuoteServiceClient : System.ServiceModel.ClientBase<Ks.Customer.ReferenciaSony.SonyQuoteService>, Ks.Customer.ReferenciaSony.SonyQuoteService {
        
        public SonyQuoteServiceClient() {
        }
        
        public SonyQuoteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SonyQuoteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SonyQuoteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SonyQuoteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void initiate() {
            base.Channel.initiate();
        }
        
        public void initiateAsync() {
            base.Channel.initiateAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios.SonyQuoteService.com/", ConfigurationName="ReferenciaSony.SonyQuoteServiceCallback")]
    public interface SonyQuoteServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute()]
        void onResult();
        
        [System.ServiceModel.OperationContractAttribute()]
        void onResultAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SonyQuoteServiceCallbackChannel : Ks.Customer.ReferenciaSony.SonyQuoteServiceCallback, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SonyQuoteServiceCallbackClient : System.ServiceModel.ClientBase<Ks.Customer.ReferenciaSony.SonyQuoteServiceCallback>, Ks.Customer.ReferenciaSony.SonyQuoteServiceCallback {
        
        public SonyQuoteServiceCallbackClient() {
        }
        
        public SonyQuoteServiceCallbackClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SonyQuoteServiceCallbackClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SonyQuoteServiceCallbackClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SonyQuoteServiceCallbackClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void onResult() {
            base.Channel.onResult();
        }
        
        public void onResultAsync() {
            base.Channel.onResultAsync();
        }
    }
}
