//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ks.Ordenes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordenes
    {
        public int ordenId { get; set; }
        public string nombreAoellidoCliente { get; set; }
        public string direccionCliente { get; set; }
        public string ciudadCliente { get; set; }
        public string paisCliente { get; set; }
        public string nombreProveedorLogisticaEnvio { get; set; }
    }
}
