//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ks.CreditCards.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCards
    {
        public int CrediCardNumber { get; set; }
        public string TypeCard { get; set; }
        public string CheckCode { get; set; }
        public string ExpirationDate { get; set; }
        public string NameCard { get; set; }
    }
}
