//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ks.Customer_Address.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Address
    {
        public string CustId { get; set; }
        public string AddressId { get; set; }
    }
}
