//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ks.Customer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string CustID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string PhoneNumber { get; set; }
        public string EMail { get; set; }
        public string Password { get; set; }
        public string CreditCardType { get; set; }
        public string CrediCardNumber { get; set; }
        public string Status { get; set; }
        public string IdCategory { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public int ROL_NCODE { get; set; }
    }
}
