//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ks.Invoices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        public string IdInvoince { get; set; }
        public Nullable<System.DateTime> DateProcess { get; set; }
        public string CustID { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
    }
}
