CREATE TABLE [dbo].[CustomerCreditCard](
	[CrediCardNumber] [int] NOT NULL,
	[CustID] [nchar](40) NOT NULL,
	[Status] [nchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[CustID] ASC,
	[CrediCardNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO