CREATE TABLE [dbo].[PIC_ROLE_USER](
	[RUS_NCODE] [int] IDENTITY(1,1) NOT NULL,
	[USE_NCODE] [int] NULL,
	[ROL_NCODE] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[RUS_NCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

