CREATE TABLE [dbo].[PIC_ROLES](
	[ROL_NCODE] [int] IDENTITY(1,1) NOT NULL,
	[ROL_CDESCRIPTION] [varchar](500) NULL,
PRIMARY KEY CLUSTERED 
(
	[ROL_NCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
