CREATE TABLE [dbo].[PIC_USERS](
	[USE_NCODE] [int] IDENTITY(1,1) NOT NULL,
	[USE_CNAME] [varchar](500) NULL,
	[USE_CSURNAME] [varchar](500) NULL,
	[USE_CEMAIL] [varchar](500) NULL,
	[USE_CPASSWORD] [varchar](500) NULL,
	[USE_CADDRESS] [varchar](500) NULL,
	[USE_CCOUNTRY] [varchar](500) NULL,
	[USE_CCITY] [varchar](500) NULL,
PRIMARY KEY CLUSTERED 
(
	[USE_NCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO