//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ks.Orders.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public string CustId { get; set; }
        public string OrdId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
    }
}
