//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAfiliaciones
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluacion
    {
        public int IdEvaluacion { get; set; }
        public string Cifin { get; set; }
        public string Sarlaft { get; set; }
        public System.DateTime UltimaEvaluacion { get; set; }
        public string identificationNumber { get; set; }
        public string identificationType { get; set; }
    }
}
